(defmacro create-load-package-defun (name)
  (list 'defun (intern (concat "load-package-" name)) '()
    (list 'interactive)
    (list 'require (list 'quote (intern (concat name "-load"))))))

(dolist (file (directory-files (file-name-directory load-file-name) nil "^.+-load\\.el$"))
  (let ((package-name (replace-regexp-in-string "-load\\.el$" "" file)))
    (message "%s" package-name)
    (eval (macroexpand `(create-load-package-defun ,package-name)))))

(defun load-package-java()
  (interactive)
  (load-package-jdee)
  (load-package-jalopy)
  (load-package-flymake)
  (load-package-jmaker)
  (load-package-jsee))

(defun load-package-all()
  (interactive)
  (load-package-elpa)
  (load-package-x-clipboard)
  (load-package-bracket)
  (load-package-tab)
  (load-package-color-theme)
  (load-package-cedet)
  (load-package-ecb)
  (load-package-yasnippet)
  (load-package-table)
  (load-package-elib)
  (load-package-cscope)
  (load-package-java)
  (load-package-go))

(defun load-package(packages)
  (interactive)
  (if (listp packages)
    (dolist (f (append packages '()))
      (funcall (intern (concat "load-package-" (symbol-name f)))))
    nil))

(provide 'package-load-define)
